### PR TITLE
TIFF fax3 2D (CCITT T.4) and fax 4 (CCITT T.6) implemented, working fine.

### PR DESCRIPTION
**Pull request by nabbla**
Don't hurry to merge it, I hope to make some more commits soon and put them here. 

Progress so far:
- Fax3 2D and Fax4 decoders implemented,
- after last merge it didn't compile in Delphi 7, now it does. (TBitmap.AlphaFormat property didn't exist back then, messed a little with conditionals)
- tried to remove all the warnings, be it implicit conversion from AnsiString to String, combining signed and unsigned values, deprecated functions, inline functions which require to add another unit to unwrap
and so on. All the warnings left are in 3rd party code, didn't work with it yet.

- Cleaned up a little, removed already 'commented' code for JPEG compression, some dublicating parts which are called executed just once were implemented as a procedure and so on.

### CODE REVIEW

**Comment by mike-lischke** [comment]
Oh great, I'm so glad to see progress here...

**Comment by nabbla** [comment]
Call me crazy Russian bicycle inventor, but I've implemented baseline JPEG decoder "from scratch" for old Tiff library. Works with all test files from original test suite. Pretty compact.

So, now it is 100% native Delphi code, easy to maintain. I was thinking about implementing arithmetic coding type of JPEG as well, Delphi own JPEG decoder (as well as libJPEG) still can't handle it though patents are expired already.

Also, fixed CMYK16 and Lab16 handling, first failed because 16-bit samples should be swapped from network order into Intel order, the second used 0..255 range instead of 0..65535. 

Hope to try x64 soon and then clean up a little...

**Comment by mike-lischke** [comment]
You are a crazy Russian bicydle inventor ;-) Doing all that in pure Delphi code is just awesome. Much easier to rebuild than to have a C compiler around for the C libs. Just let me know when you think I can merge.

**Comment by nabbla** [comment]
Well, this is time :)

Compiles on x64 as well as on x86 (and still works on Delphi 7), all the files from test suite are opened normally on both versions. OJPEG still not supported, as well as L16/Luv24/Luv32 with SCILog compression. All the others are opened correctly.

**Comment by mike-lischke** [comment]
Ok, many thanks for that. Do you think we can merge now?

**Comment by nabbla** [comment]
Yes, it's in good condition.

**Comment by baeckerg** [comment]
Kudos to "The crazy bicycle inventor" - will it work with FMX as well?

**Comment by mike-lischke** [comment]
@nabbla I think you should add yourself to the copyright headers everywhere you changed something, to add proper attribution for your work. Make this a new pull request.

**Comment by nabbla** [comment]
@baeckerg Not yet: FMX has another TBitmap, not compatible with VCL one, also TColor not exist any more, TAlphaColor instead, etc.

I'll try to make it FMX-compatible soon. 

@mike-lischke yep, it seems new pull request is needed after all, with copyright and FMX support :)

**Comment by nabbla** [comment]
@baeckerg, I looked at FMX graphic system more thoroughly, it varies much more than I thought. No way to descend from TBitmap (it has static methods), need to descend from TBitmapCodec instead. That's not just couple of IFDEFS, high-level structure of GraphicEx should be changed to support both VCL and FMX. Like, have VCL.GraphicEx unit, FMX.GraphicEx unit which accomodate all library-specific code.  Will think about it.

**Comment by baeckerg** [comment]
Many thanks for looking into it. It looks like the FMX system has certain advantages but I do understand your point that it is much more than a couple of IFDEFs. Just keep us posted whether you consider it to be worthwhile your time - maybe you will also become the crazy inventor of sliced bread 8-)

**Pull request merged**
