### PR TITLE
Basic saving capabilities

### PR DESCRIPTION
**Pull request by nabbla**
-  ftEnableSaving flag introduced for TFormatTypes, it should be set for graphic formats with supported SaveToFile procedure. So if we have SavePictureDialog (or plain SaveDialog), at startup (formCreate or smth like that) we write:

SavePictureDialog.Filter:=FileFormatList.GetGraphicFilter([ftEnableSaving],fstNone,[foIncludeExtension],nil);

-  UnregisterFileFormat changed a bit to allow replacing some of file formats with third-party libs without memory leak or access violation. Situation like this is handled:

//initialization section
RegisterFileFormat('png', gesPortableNetworkGraphic, '', [ftRaster], False, TPNGGraphic);

//FormCreate
FileFormatList.RegisterFileFormat('png', gesPortableNetworkGraphic, '',[ftRaster,ftEnableSaving], True, TPNGObject);

//finalization section
UnregisterFileFormat('', TPNGGraphic);

After TPNGGraphic is replaced with TPngObject, Unregister procedure doesn't find already removed entry and stops.

- SaveGraphicToFile(source: TGraphic; FileName: string) introduced, it determines by file extension, what file format to save and performs conversion if it's needed. For TBitmap descendants, source is drawed in Canvas, native formats which are not TBitmap are handled individually.
At last, if we have third-party TGraphic which is not TBitmap, we try to use Assign procedure to convert source to this format. For pngimage lib it works.

Simplest demo program included.

### CODE REVIEW

**Comment by mike-lischke** [comment]
nabla, thanks for your contribution. In the first patch you are adding a pure obj file (zutils) and you are using the strUtils unit. What are those 2 about? Why are they needed?

Additionally, can you please format your source code so that it matches the existing format (e.g. a space char after punctuation, like a comma, indentation/alignment of comments, spaces around operators)?

**Comment by nabbla** [comment]
Sorry, I used older version of GraphicEx and made some mistakes trying to sync my changes to latest version of lib. zutils.obj seemed to be missing in zlib folder (all other obj files were in place) so I put it there, but TIFF refused to compile anyway (unsatisfied declaration of _llmod, @zcalloc, @zcfree etc)

I'll try to understand what's wrong and make it compile on different versions of Delphi, but it requires some time.

By the way, in latest version, JPEG formats were disabled, it seems no problem to enable them by uncommenting code and adding JPEG to "uses". Should work on all delphi versions, won't work on Kylix, possible on Lazarus if remove JPEG in "uses" clause. TJPEGImage exists in Lazarus OK.

I've fixed formatting of my code and added comments. 

This code was tested for some months and seems to work OK. Also, FastMM4 memory manager was used with enabled memory leaks detection and no leaks are found. 

By now, saving is enabled for:
- BMP
- WMF and EMF
- JPG, JPEG, JFIF, JPE
- PNG, if using PNGDelphi lib (https://github.com/JoseJimeniz/pngdelphi). It fits in just fine (in test program uncomment top line  {$define UsePNGImage} and add pngdelphi files to project.

**Comment by mike-lischke** [comment]
Ok, that looks good. Thank you. So, I guess this also means that GraphicEx compiles fine for you. What Delphi version do you use?

**Comment by nabbla** [comment]
Sorry for so long absence. I used Delphi 7 for a long time and didn't manage to compile newest version of GraphicEx with all the formats enabled. I just disabled some of them, checked that the remaining ones work fine and my changes as well and that was all.

Finally, I've bought Delphi 10 Seattle and downloaded all the previous versions and what's more important, got some experience with migrating between old non-Unicode versions and new ones and also linking to C libraries, so now I'll try to make it work.

**Comment by mike-lischke** [comment]
Welcome back :-) Would be great if you could make the lib compile in latest Delphi. I'm ready to accept more contributions! Just open a new pull request. Thanks.

**Comment by nabbla** [comment]
Ok, it seems to work almost normally (didn't pull request yet, want to struggle a little bit more at first, there it is: https://github.com/nabbla/GraphicEx/commit/4268b734bef17bbed6977c9225b882d674fcb2ad),
but TIFF library is behaving strangely. In Delphi7 it opens most of files normally but another ones
 (True Color / Full (LZW).tif
Full (multi image) RGB.tif
 Full (OJPEG) YCbCr.tif
 Full (OJPEG High) CMYK.tif 
ZIP RGB 16.tif)
not just fail, but raise AV.

In newer versions it's even funnier: all the same images can be loaded as before, but with every single one debugger stops executing several times at 'non-user breakpoints' warning 'Heap block modified at ... past requested size ...'.

Did you have problems with it before? For me sprintf() function from LibStub seems suspicious: it has Delphi calling convention and Delphi-only feature of open array param. Most of AV when loading .tif happen exactly in it: just at 'begin' line of code, maybe there is stack corruption, though it recovers surprisingly well from it (program doesn't stop working, just shows error and stops loading image). I can't understand where it is called from, I tried to find sprintf call in tiff library but didn't find it!

**Comment by nabbla** [comment]
Another commit: https://github.com/nabbla/GraphicEx/commit/1dedf86313763944376f72b5dd3ecdf47d6d4966

couple more days and I'll be brave enough to pull another request :)

**Comment by mike-lischke** [comment]
nabbla, that looks very promising. Can't wait to see the final solution. Btw, if you think that you can go with a pure Pascal solution instead of the intermediate ASM code then by all means go for it. No need to put all that in ifdefs. I used ASM solely for speed reasons - somtimes it was also simpler to do e.g. a simple shift in ASM. But I believe meanwhile compiles are clever enough to make good machine code from source code, maybe even better than a human can do, so IMO going with normal Delphi code instead of ASM should be fine as well.

**Comment by nabbla** [comment]
Saw new issue and decided to pull request after all.

Unfortunately, Delphi compiler is still not smart enough to compete with hand-written assembler, so I don't want to trash all this working asm code. Of course computers are much more powerful today, but images are getting larger, too! Don't know, it's eternal struggle between code performance and its elegance. Maybe the most elegant way for GraphicColors is to convert anything to XYZ (by the way using ICC profiles if available) and than from XYZ to anything else, this way we have 2*N converters for N different formats, not almost N^2 as for now, but speed penalty might be significant... 

There is real problem with CMYK to RGB conversion, though, faces get greenish. I was advised to use CMS here and set SWOP profile for CMYK and sRGB for RGB by default (if no other explicit colorimetry information is present). Could try to implement later :) 

OK, I'll check my code formatting, I agree that it is important.

**Pull request merged**
